---
title: "aRt tier list"
format: html
editor: visual
---

This is a reference for me since there are so many functions in this package
```{r,include=FALSE}
library(aRt)
```

## Coolest

```{r}
bricks()
```

```{r}
chaos()
```

```{r}
fractals()
```

```{r}
rings()
```

```{r}
spirals()
```

```{r}
squiggles()
```

```{r}
sunsets()
```

```{r}
tiles()
```

```{r}
wander()
```

## Cool

```{r}
attraction()
```

```{r}
black_hole()
```

```{r}
boxes()
```

```{r}
crawling()
```

```{r}
divide()
```

```{r}
moire()
```

```{r}
perpendicular()
```

```{r}
rectangles()
```

```{r}
shatter()
```

```{r}
spiro()
```

```{r}
split_grid()
```

```{r}
squares()
```

```{r}
streams()
```

```{r}
vortex()
```

## Mid

```{r}
bullseye()
```

```{r}
circles()
```

```{r}
circular()
```

```{r}
criss_cross()
```

```{r}
crosshatch()
```

```{r}
imploding_hexagon()
```

```{r}
mosaic_sketch()
```

```{r}
puzzles()
```

```{r}
random_tessellation()
```

```{r}
riso_circles()
```

```{r}
split_jitter()
```

```{r}
stacked()
```

```{r}
waves()
```

## Kinda Boring

```{r}
abacus()
```

```{r}
blending()
```

```{r}
bubbles()
```

```{r}
dots()
```

```{r}
fading()
```

```{r}
gradients()
```

```{r}
heart()
```

```{r}
infinity()
```

```{r}
mirrored()
```

```{r}
polygons()
```

```{r}
riley()
```

```{r}
shells()
```

```{r}
smudge()
```

```{r}
static()
```

```{r}
stripes()
```

```{r}
sunbursts()
```

```{r}
sunbursts_panel()
```

```{r}
window_boxes()
```

## Awkwardly slow

```{r,eval=FALSE}
flow_fields()
```

## Broken for me

```{r,eval=FALSE}
connected()
```

```{r,eval=FALSE}
contours()
```
